# Generated by Django 2.1.15 on 2020-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('LastName', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Address1', models.CharField(blank=True, max_length=255, null=True)),
                ('Address2', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=12, null=True)),
                ('State', models.CharField(blank=True, max_length=255, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Link_Linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('Link_Linkedin_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Link_Linkedin_Comment', models.URLField(blank=True, max_length=1000, null=True)),
                ('Link_Github', models.URLField(blank=True, max_length=500, null=True)),
                ('Link_Github_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Link_Github_Comment', models.URLField(blank=True, max_length=1000, null=True)),
                ('Link_DataViz', models.URLField(blank=True, max_length=500, null=True)),
                ('Link_DataViz_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Link_DataViz_Comment', models.URLField(blank=True, max_length=1000, null=True)),
                ('Link_Website', models.URLField(blank=True, max_length=500, null=True)),
                ('Link_Website_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Link_Website_Comment', models.URLField(blank=True, max_length=1000, null=True)),
                ('Resume', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('Picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('PictureLink', models.URLField(blank=True, max_length=500, null=True)),
                ('Embedded_Code', models.CharField(blank=True, max_length=8000, null=True)),
                ('Comments', models.CharField(blank=True, max_length=4000, null=True)),
                ('Current_Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Current_Employeer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
