# Generated by Django 2.1.15 on 2020-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='Link_DataViz_Comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Link_Github_Comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Link_Linkedin_Comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Link_Website_Comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
