# Generated by Django 2.1.15 on 2020-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201004_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='Link_DataViz_Embed',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='Link_Github_Embed',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='Link_Linkedin_Embed',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='Link_Website_Embed',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
