# Generated by Django 2.1.15 on 2020-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201004_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usecases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(blank=True, max_length=4000, null=True)),
                ('Modifications', models.CharField(blank=True, max_length=4000, null=True)),
                ('PictureLink', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
