# Generated by Django 2.1.15 on 2020-10-04 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('priority', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('submission_dts', models.DateTimeField(default=django.utils.timezone.now)),
                ('requestor', models.CharField(max_length=255)),
                ('requestor_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BugCategoryTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=512)),
                ('comment_dts', models.DateTimeField(default=django.utils.timezone.now)),
                ('bug_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bug.Bug')),
            ],
        ),
        migrations.CreateModel(
            name='BugPriorityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BugWorkqueueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workqueue_status', models.CharField(max_length=255)),
                ('workqueue_comment', models.CharField(max_length=512)),
                ('workqueue_lastupdatedts', models.DateTimeField(default=django.utils.timezone.now)),
                ('bug_wq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='bug.Bug')),
                ('workqueue_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugWorkqueueStatusTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statustype', models.CharField(max_length=255)),
            ],
        ),
    ]
